android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
# Batasi RAM maksimal buat Gradle Daemon (misal kasih 3GB atau 4GB aja, jangan dilepas liar)
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC

# Jalankan Kapt di dalam proses Gradle yang sama biar gak bikin proses java baru lagi
kapt.use.worker.api=true
kapt.incremental.apt=true
